service: learnn-game-be

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: eu-central-1
  logs:
    restApi: true
  environment:
    NODE_ENV: ${self:provider.stage}
    DB_HOST: ${file(./environment/${self:provider.stage}.environment.json):DB_HOST}
    DB_NAME: ${file(./environment/${self:provider.stage}.environment.json):DB_NAME}

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  createGame:
    handler: app/handler.createGame
    events:
      - http:
          cors: true
          path: games
          method: post

  findAllGames:
    handler: app/handler.findAllGames
    events:
      - http:
          cors: true
          path: games
          method: get
